version: '3'
services:
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    php:
        build: .docker/php
        ports:
            - "5173:5173"
        volumes:
            - ./www:/var/www/
        depends_on:
            - db
        command: >
            bash -c "
              if [ ! -f /var/www/html/install.lock ]; then
                echo 'Starting setup...' &&
                wait-for-it db:3306 -t 60 &&
                cp config-dist.php config.php &&
                cp admin/config-dist.php admin/config.php &&
                chmod 777 config.php &&
                chmod 777 admin/config.php &&
                php /var/www/html/install/cli_install.php install --username admin --password admin --email email@example.com --http_server http://localhost/ --db_driver mysqli --db_hostname db --db_username root --db_password opencart --db_database opencart --db_port 3306 --db_prefix oc_ &&
                touch /var/www/html/install.lock &&
                echo 'Setup complete';
              else
                echo 'Setup already done';
              fi &&
              php-fpm"

    ####################################################################################################
    # DATABASE (MariaDB)
    ####################################################################################################
    db:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: opencart
            MYSQL_DATABASE: opencart
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - .docker/redis/data:/data
    memcached:
        image: memcached:latest
